# Generated by Django 4.0.4 on 2022-06-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_donacion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.IntegerField()),
            ],
        ),
    ]
