# Generated by Django 4.0.4 on 2022-06-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_descuentodonacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='desc',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.descuentodonacion'),
        ),
    ]
