# Generated by Django 4.0.4 on 2022-06-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_descuentodonacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentodonacion',
            name='nombre',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
