# Generated by Django 4.0.4 on 2022-06-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_descuentodonacion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuentodonacion',
            name='desc',
        ),
    ]
