# Generated by Django 4.0.4 on 2022-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_donacion_desc_delete_descuentodonacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoDonacion',
            fields=[
                ('id', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('desc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
