# Generated by Django 4.0.4 on 2022-06-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_donacion_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='desc',
        ),
        migrations.DeleteModel(
            name='DescuentoDonacion',
        ),
    ]
