# Generated by Django 4.0.4 on 2022-06-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_donacion_desc_delete_descuentodonacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='desc',
            field=models.IntegerField(default=0.15),
        ),
    ]
