# Generated by Django 4.0.4 on 2022-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_donacion_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
