# Generated by Django 4.0.4 on 2022-06-22 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_alter_donacion_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='desc',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
    ]
