# Generated by Django 4.0.4 on 2022-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_donacion_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='nombrecompleto',
            new_name='nombredonante',
        ),
        migrations.AlterField(
            model_name='donacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
