# Generated by Django 4.0.4 on 2022-06-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_donacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='user',
        ),
    ]
