# Generated by Django 4.0.4 on 2022-06-25 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_remove_donacion_correo_remove_donacion_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='suscriptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
