# Generated by Django 4.0.4 on 2022-07-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_enviodireccion_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviodireccion',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
    ]
